[package]
name = "apalis-dep-problem"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
apalis = { version = "0.4.6", default-features = false, features = ["chrono", "tokio-comp"] }